### ISSUE TITLE
AWS SDK Instrumentation should use AWS SDK valus for `rpc` attributes

### ISSUE THREAD

**Issue by NathanielRN** [aspecto-io/opentelemetry-ext-js#160]
# Description

In the aws sdk instrumentation package, `rpc` attributes are set from the `normalizedRequest`.

https://github.com/aspecto-io/opentelemetry-ext-js/blob/243e19bcebb5f95df5b4a68cbf675aa6351ca3fb/packages/instrumentation-aws-sdk/src/utils.ts#L40-L47

`normalizedRequest` (v2 and v3) modify the request metadata values returned from the AWS SDK like this:

https://github.com/aspecto-io/opentelemetry-ext-js/blob/243e19bcebb5f95df5b4a68cbf675aa6351ca3fb/packages/instrumentation-aws-sdk/src/utils.ts#L15-L23

Specifically:
* It converts the `service` name `.toLowerCase()`
* It converts the `operation` name `.toCamelCase()`

However, [the specs for AWS SDK instrumentation](https://github.com/open-telemetry/opentelemetry-specification/blob/342255820f6affd9e21409a8567242b979efc8c0/semantic_conventions/trace/instrumentation/aws-sdk.yml#L18-L27) give examples that contradict these patterns.

```yaml
- ref: rpc.service
brief: "The name of the service to which a request is made, as returned by the AWS SDK."
examples:
    - DynamoDB
    - S3
- ref: rpc.method
brief: "The name of the operation corresponding to the request, as returned by the AWS SDK"
examples:
    - GetItem
    - PutItem
```

# Action Items

Based on the examples, we should return `S3` instead of `s3` and `ListBuckets` instead of `listBuckets` (for example).

This means using `toUpperCase()` and a modified version of `toCamelCase()` with the first character Upper Case.
